### ISSUE TITLE
Entities and devices are getting mixed when there are more than one main module linked to account

### ISSUE THREAD

**Issue by bpawulski** [anarion80/tech#8]
Hi, huge thanks for forking this project and taking care of it !!!

I have setup with dual L8 modules (one is for ground floor and the second for upper one). During setup, the integration discovers both modules and allow for puling info from them. But the entities are getting mixed between modules. For example:
 1. only one module shows the battery sensors for controllers. 
<img width="1078" alt="Screenshot 2024-03-20 at 16 28 06" src="https://github.com/anarion80/tech/assets/148430024/550f468d-e527-45d1-b516-5d0af0635cc1">
 2. I have a single outside temp sensor connected to ground floor L8 module (called "Dol"), but the integration shows it in both hubs. The other one shows constant -200 deg C. 
 
 3. I believe somehow the IDs from one hub are mixed with IDs from the other 
<img width="1400" alt="Screenshot 2024-03-20 at 16 29 02" src="https://github.com/anarion80/tech/assets/148430024/071d5276-7185-4223-92c3-612a0f2dc544">
For example above GarderobaD -> is room downstairs connected to "Dol" hub, but the sensor names jasiek_temperature, jasiek_battery are mixed with the upper floor room called "jasiek" ("Gora" hub)

Not sure what logs (and how) i could gather to help narrowing this problem

**Comment by anarion80** [comment]
Ok, looks like device naming is not unique enough.

So first of all, please use the newly released version 2 from official, upstream repo: https://github.com/mariusz-ostoja-swierczynski/tech-controllers
I will close the issue here, and please open again over there.

Enable debug logs in home assistant:
![image](https://github.com/anarion80/tech/assets/2185791/df876cd1-0f15-47aa-8310-c6e9c5152a3d)
remove the hubs, add again. Disable debug logs and attach in the issue.

And ideally also capture json response from emodul: https://github.com/anarion80/tech/issues/5#issuecomment-1999394111

**Comment by bpawulski** [comment]
done
